function equilibrium_state_mmHg = circulation_equilibrium_state( ...
    params, total_filling_volume_ml, systemic_arterial_resistance, cardiac_gain)
%CIRCULATION_EQUILIBRIUM_STATE Solve the equilibrium state for a fixed total volume.

compliance = params.model.compliance_ml_per_mmHg;
resistance = params.model.resistance_mmHg_s_per_ml.systemic_venous;
pra_offset = params.model.pra_flow_offset_mmHg;

equilibrium_matrix = [ ...
    1, -1, -cardiac_gain * systemic_arterial_resistance; ...
    0, 1, -(1 + cardiac_gain * resistance); ...
    compliance.systemic_arterial, compliance.systemic_venous, compliance.right_atrial];

equilibrium_rhs = [ ...
    -cardiac_gain * systemic_arterial_resistance * pra_offset; ...
    -cardiac_gain * resistance * pra_offset; ...
    total_filling_volume_ml];

equilibrium_state_mmHg = equilibrium_matrix \ equilibrium_rhs;
end
