function [A, b, B] = circulation_state_space(params, systemic_arterial_resistance, cardiac_gain)
%CIRCULATION_STATE_SPACE State-space matrices for the circulation model.

compliance = params.model.compliance_ml_per_mmHg;
resistance = params.model.resistance_mmHg_s_per_ml;
pra_offset = params.model.pra_flow_offset_mmHg;

A = [ ...
    -1 / (systemic_arterial_resistance * compliance.systemic_arterial), ...
     1 / (systemic_arterial_resistance * compliance.systemic_arterial), ...
     cardiac_gain / compliance.systemic_arterial; ...
     1 / (systemic_arterial_resistance * compliance.systemic_venous), ...
    -1 / (systemic_arterial_resistance * compliance.systemic_venous) ...
        - 1 / (resistance.systemic_venous * compliance.systemic_venous), ...
     1 / (resistance.systemic_venous * compliance.systemic_venous); ...
     0, ...
     1 / (resistance.systemic_venous * compliance.right_atrial), ...
    -1 / (resistance.systemic_venous * compliance.right_atrial) ...
        - cardiac_gain / compliance.right_atrial];

b = [ ...
    -cardiac_gain * pra_offset / compliance.systemic_arterial; ...
     0; ...
     cardiac_gain * pra_offset / compliance.right_atrial];

B = [0; 1 / compliance.systemic_venous; 0];
end
