function params = circulation_params()
%CIRCULATION_PARAMS Shared parameters for the circulation modeling project.

q0_ml_s = 5 / 60 * 1000;
psa0_mmHg = 100;
psv0_mmHg = 5;
pra0_mmHg = 4;
pra_flow_offset_mmHg = 1.82;

params.model.nominal_cardiac_output_ml_s = q0_ml_s;
params.model.nominal_pressures_mmHg = struct( ...
    "systemic_arterial", psa0_mmHg, ...
    "systemic_venous", psv0_mmHg, ...
    "right_atrial", pra0_mmHg);
params.model.pra_flow_offset_mmHg = pra_flow_offset_mmHg;
params.model.compliance_ml_per_mmHg = struct( ...
    "systemic_arterial", 4, ...
    "systemic_venous", 111, ...
    "right_atrial", 31);
params.model.resistance_mmHg_s_per_ml = struct( ...
    "systemic_arterial", (psa0_mmHg - psv0_mmHg) / q0_ml_s, ...
    "systemic_venous", (psv0_mmHg - pra0_mmHg) / q0_ml_s);
params.model.cardiac_gain_ml_s_per_mmHg = ...
    q0_ml_s / (pra0_mmHg - pra_flow_offset_mmHg);

params.simulation.default_dt_s = 0.1;

params.hemorrhage.start_time_s = 10;
params.hemorrhage.duration_s = 50;
params.hemorrhage.volume_loss_ml = 400;

params.baseline.duration_s = 100;

params.validation.duration_s = 50;
params.validation.initial_arterial_pressure_scale = 1.5;

params.control.duration_s = 150;
params.control.tau_resistance_s = 15;
params.control.tau_cardiac_gain_s = 5;
params.control.resistance_feedback_gain = ...
    params.model.resistance_mmHg_s_per_ml.systemic_arterial / psa0_mmHg * 0.6;
params.control.cardiac_gain_feedback_gain = ...
    params.model.cardiac_gain_ml_s_per_mmHg / psa0_mmHg * 15;

params.plot.font_size = 16;
params.plot.line_width = 1.5;
params.plot.colors = struct( ...
    "open_loop", [0.00, 0.45, 0.74], ...
    "controlled", [0.85, 0.33, 0.10], ...
    "eigen", [0.47, 0.67, 0.19], ...
    "matrix_exponential", [0.49, 0.18, 0.56]);

params.output.common_figure_filenames = [ ...
    "systemic_arterial_pressure.jpg", ...
    "systemic_venous_pressure.jpg", ...
    "right_atrial_pressure.jpg", ...
    "cardiac_output.jpg", ...
    "systemic_filling_volume.jpg"];
params.output.feedback_adaptation_filename = "feedback_adaptation.jpg";
end
