function figure_handle = plot_control_adaptation(controlled_results, params)
%PLOT_CONTROL_ADAPTATION Plot controller-driven changes in Rsa and Kr.

figure_handle = figure("Name", "Feedback Adaptation", "Color", "w");
tiledlayout(2, 1)

nexttile
plot( ...
    controlled_results.time_s, ...
    controlled_results.systemic_arterial_resistance_mmHg_s_per_ml, ...
    "LineWidth", params.plot.line_width, ...
    "Color", params.plot.colors.controlled)
hold on
yline( ...
    params.model.resistance_mmHg_s_per_ml.systemic_arterial, ...
    "--", ...
    "Baseline", ...
    "LineWidth", params.plot.line_width)
grid on
box on
title("Systemic Arterial Resistance", "FontSize", params.plot.font_size)
xlabel("Time (s)", "FontSize", params.plot.font_size)
ylabel("mmHg/(mL/s)", "FontSize", params.plot.font_size)
set(gca, "FontSize", params.plot.font_size)

nexttile
plot( ...
    controlled_results.time_s, ...
    controlled_results.cardiac_gain_ml_s_per_mmHg, ...
    "LineWidth", params.plot.line_width, ...
    "Color", params.plot.colors.controlled)
hold on
yline( ...
    params.model.cardiac_gain_ml_s_per_mmHg, ...
    "--", ...
    "Baseline", ...
    "LineWidth", params.plot.line_width)
grid on
box on
title("Cardiac Gain", "FontSize", params.plot.font_size)
xlabel("Time (s)", "FontSize", params.plot.font_size)
ylabel("mL/(s*mmHg)", "FontSize", params.plot.font_size)
set(gca, "FontSize", params.plot.font_size)
end
