function verify_circulation_project()
%VERIFY_CIRCULATION_PROJECT Lightweight execution and sanity checks.

close all

project_root = fileparts(mfilename("fullpath"));
addpath(fullfile(project_root, "shared"));

params = circulation_params();
nominal = params.model.nominal_pressures_mmHg;

baseline_dir = fullfile(project_root, "baseline_hemorrhage");
methods_dir = fullfile(project_root, "methods_validation");
feedback_dir = fullfile(project_root, "feedback_control");

run_and_check_outputs( ...
    fullfile(baseline_dir, "run_baseline_hemorrhage.m"), ...
    fullfile(baseline_dir, "figures"), ...
    params.output.common_figure_filenames);
baseline_config.time_s = 0:params.simulation.default_dt_s:params.baseline.duration_s;
baseline_config.initial_state_mmHg = [ ...
    nominal.systemic_arterial; ...
    nominal.systemic_venous; ...
    nominal.right_atrial];
baseline_config.volume_input_ml_s = make_hemorrhage_profile( ...
    baseline_config.time_s, params.hemorrhage);
baseline_results = simulate_open_loop_circulation(params, baseline_config);
assert_valid_result_struct(baseline_results, "baseline_results");
close all

run_and_check_outputs( ...
    fullfile(methods_dir, "run_methods_validation.m"), ...
    fullfile(methods_dir, "figures"), ...
    params.output.common_figure_filenames);
validation_config.time_s = 0:params.simulation.default_dt_s:params.validation.duration_s;
validation_config.initial_state_mmHg = [ ...
    params.validation.initial_arterial_pressure_scale * nominal.systemic_arterial; ...
    nominal.systemic_venous; ...
    nominal.right_atrial];
validation_config.volume_input_ml_s = zeros(size(validation_config.time_s));
analytic_validation = solve_linear_circulation_analytic(params, validation_config);
validation_results = [ ...
    simulate_open_loop_circulation(params, validation_config), ...
    analytic_validation.eigen, ...
    analytic_validation.matrix_exponential];
for idx = 1:numel(validation_results)
    assert_valid_result_struct(validation_results(idx), sprintf("validation_results(%d)", idx));
end
close all

feedback_files = [ ...
    params.output.common_figure_filenames, ...
    params.output.feedback_adaptation_filename];
run_and_check_outputs( ...
    fullfile(feedback_dir, "run_feedback_control.m"), ...
    fullfile(feedback_dir, "figures"), ...
    feedback_files);
feedback_config.time_s = 0:params.simulation.default_dt_s:params.control.duration_s;
feedback_config.initial_state_mmHg = [ ...
    nominal.systemic_arterial; ...
    nominal.systemic_venous; ...
    nominal.right_atrial];
feedback_config.volume_input_ml_s = make_hemorrhage_profile( ...
    feedback_config.time_s, params.hemorrhage);
open_loop_results = simulate_open_loop_circulation(params, feedback_config);
controlled_results = simulate_feedback_control_circulation(params, feedback_config);
assert_valid_result_struct(open_loop_results, "open_loop_results");
assert_valid_result_struct(controlled_results, "controlled_results");
close all

disp("VERIFY_OK_CIRCULATION_PROJECT")
end

function run_and_check_outputs(script_path, output_dir, expected_files)
for idx = 1:numel(expected_files)
    output_file = fullfile(output_dir, expected_files(idx));
    if exist(output_file, "file")
        delete(output_file);
    end
end

run(script_path);

for idx = 1:numel(expected_files)
    output_file = fullfile(output_dir, expected_files(idx));
    assert(exist(output_file, "file") == 2, ...
        "Expected output file was not created: %s", output_file);

    file_info = dir(output_file);
    assert(~isempty(file_info) && file_info.bytes > 0, ...
        "Output file is empty: %s", output_file);
end
end

function assert_valid_result_struct(results, label)
required_fields = { ...
    "time_s", ...
    "systemic_arterial_pressure_mmHg", ...
    "systemic_venous_pressure_mmHg", ...
    "right_atrial_pressure_mmHg", ...
    "cardiac_output_ml_s", ...
    "filling_volume_ml"};

for field_idx = 1:numel(required_fields)
    field_name = required_fields{field_idx};
    assert(isfield(results, field_name), "%s is missing field %s.", label, field_name);
    values = results.(field_name);
    assert(~isempty(values), "%s.%s is empty.", label, field_name);
    assert(all(isfinite(values)), "%s.%s contains NaN or Inf.", label, field_name);
end

num_points = numel(results.time_s);
assert(num_points > 1, "%s.time_s must contain more than one point.", label);
assert(all(diff(results.time_s) > 0), "%s.time_s must be strictly increasing.", label);

fields_to_match = { ...
    "systemic_arterial_pressure_mmHg", ...
    "systemic_venous_pressure_mmHg", ...
    "right_atrial_pressure_mmHg", ...
    "cardiac_output_ml_s", ...
    "filling_volume_ml"};
for field_idx = 1:numel(fields_to_match)
    field_name = fields_to_match{field_idx};
    assert(numel(results.(field_name)) == num_points, ...
        "%s.%s length does not match time_s.", label, field_name);
end
end
